using Gamee_Hiukka.Control;
using Gamee_Hiukka.Data;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

[CreateAssetMenu(fileName = "CountryResources", menuName = "ScriptableObject/CountryResources")]
public class CountryResources : ScriptableObject
{
    private static CountryResources _instance;

    private const string path = "Country/CountryResources";
    public static CountryResources Instance => _instance ?? (_instance = Resources.Load<CountryResources>(path));
    public List<Country> countries;

    public List<Country> GetCountries() 
    {
        return countries;
    }

    public Sprite GetFlag(string countryCode) 
    {
        Sprite flag = null;
        foreach(var country in countries) 
        {
            if (country.countryCode.ToString().Equals(countryCode)) 
            {
                flag =  country.flag;
                break;
            }
        }
        return flag;
    }

    public int GetCountryIndexDefaut(string countryCode) 
    {
        int index = 0;
        foreach(var country in countries) 
        {
            if (country.countryCode.ToString().Equals(countryCode)) 
            {
                break;
            }
            index++;
        }

        //GameData.IndexCountryCurrent = index;
        return index;
    }

#if UNITY_EDITOR
    public readonly string[] countryName =
    {
        "Afghanistan", //"AF",
        "Aland Islands", //"AX",
        "Albania", //"AL",
        "Algeria", //"DZ",
        "American Samoa", //"AS",
        "Andorra", //"AD",
        "Angola", //"AO",
        "Anguilla", //"AI",
// "Antarctica", //"AQ", 
        "Antigua and Barbuda", //"AG",
        "Argentina", //"AR",
        "Armenia", //"AM",
        "Aruba", //"AW",
        "Australia", //"AU",
        "Austria", //"AT",
        "Azerbaijan", //"AZ",
        "Bahamas", //"BS",
        "Bahrain", //"BH",
        "Bangladesh", //"BD",
        "Barbados", //"BB",
        "Belarus", //"BY",
        "Belgium", //"BE",
        "Belize", //"BZ",
        "Benin", //"BJ",
        "Bermuda", //"BM",
        "Bhutan", //"BT",
        "Bolivia, Plurinational State of", //"BO",
        "Bonaire, Sint Eustatius and Saba", //"BQ",
        "Bosnia and Herzegovina", //"BA",
        "Botswana", //"BW",
// "Bouvet Island", //"BV",
        "Brazil", //"BR",
// "British Indian Ocean Territory", //"IO",
        "Brunei Darussalam", //"BN",
        "Bulgaria", //"BG",
        "Burkina Faso", //"BF",
        "Burundi", //"BI",
        "Cambodia", //"KH",
        "Cameroon", //"CM",
        "Canada", //"CA",
        "Cape Verde", //"CV",
        "Cayman Islands", //"KY",
        "Central African Republic", //"CF",
        "Chad", //"TD",
        "Chile", //"CL",
        "China", //"CN",
// "Christmas Island", //"CX",
// "Cocos (Keeling) Islands", //"CC",
        "Colombia", //"CO",
        "Comoros", //"KM",
        "Congo", //"CG",
        "Democratic Republic of the Congo", //"CD",
        "Cook Islands", //"CK",
        "Costa Rica", //"CR",
        "Cote D'ivoire", //"CI",
        "Croatia", //"HR",
        "Cuba", //"CU",
        "Curacao", //"CW",
        "Cyprus", //"CY",
        "Czech Republic", //"CZ",
        "Denmark", //"DK",
        "Djibouti", //"DJ",
        "Dominica", //"DM",
        "Dominican Republic", //"DO",
        "Ecuador", //"EC",
        "Egypt", //"EG",
        "El Salvador", //"SV",
        "Equatorial Guinea", //"GQ",
        "Eritrea", //"ER",
        "Estonia", //"EE",
        "Ethiopia", //"ET",
// "Falkland Islands (Malvinas)", //"FK",
        "Faroe Islands", //"FO",
        "Fiji", //"FJ",
        "Finland", //"FI",
        "France", //"FR",
        "French Guiana", //"GF",
        "French Polynesia", //"PF",
// "French Southern Territories", //"TF",
        "Gabon", //"GA",
        "Gambia", //"GM",
        "Georgia", //"GE",
        "Germany", //"DE",
        "Ghana", //"GH",
        "Gibraltar", //"GI",
        "Greece", //"GR",
        "Greenland", //"GL",
        "Grenada", //"GD",
        "Guadeloupe", //"GP",
        "Guam", //"GU",
        "Guatemala", //"GT",
        "Guernsey", //"GG",
        "Guinea", //"GN",
        "Guinea-Bissau", //"GW",
        "Guyana", //"GY",
        "Haiti", //"HT",
// "Heard Island and Mcdonald Islands", //"HM",
// "Holy See (Vatican City State)", //"VA",
        "Honduras", //"HN",
        "Hong Kong", //"HK",
        "Hungary", //"HU",
        "Iceland", //"IS",
        "India", //"IN",
        "Indonesia", //"ID",
        "Islamic Republic of Iran", //"IR",
        "Iraq", //"IQ",
        "Ireland", //"IE",
// "Isle of Man", //"IM",
        "Israel", //"IL",
        "Italy", //"IT",
// "Ivory Coast", //"IV",
        "Jamaica", //"JM",
        "Japan", //"JP",
        "Jersey", //"JE",
        "Jordan", //"JO",
        "Kazakhstan", //"KZ",
        "Kenya", //"KE",
        "Kiribati", //"KI",
// "Korea, Democratic People's Republic of", //"KP",
        "Republic of Korea", //"KR",
        "Kosovo", //"XK"
        "Kuwait", //"KW",
        "Kyrgyzstan", //"KG",
        "Lao People's Democratic Republic", //"LA",
        "Latvia", //"LV",
        "Lebanon", //"LB",
        "Lesotho", //"LS",
        "Liberia", //"LR",
        "Libya", //"LY",
        "Liechtenstein", //"LI",
        "Lithuania", //"LT",
        "Luxembourg", //"LU",
        "Macao", //"MO",
        "The Former Yugoslav Republic of Macedonia", //"MK",
        "Madagascar", //"MG",
        "Malawi", //"MW",
        "Malaysia", //"MY",
        "Maldives", //"MV",
        "Mali", //"ML",
        "Malta", //"MT",
        "Marshall Islands", //"MH",
        "Martinique", //"MQ",
        "Mauritania", //"MR",
        "Mauritius", //"MU",
        "Mayotte", //"YT",
        "Mexico", //"MX",
        "Federated States of Micronesia", //"FM",
        "Republic of Moldova", //"MD",
        "Monaco", //"MC",
        "Mongolia", //"MN",
        "Montenegro", //"ME",
        "Montserrat", //"MS",
        "Morocco", //"MA",
        "Mozambique", //"MZ",
        "Myanmar", //"MM",
        "Namibia", //"NA",
        "Nauru", //"NR",
        "Nepal", //"NP",
        "Netherlands", //"NL",
        "New Caledonia", //"NC",
        "New Zealand", //"NZ",
        "Nicaragua", //"NI",
        "Niger", //"NE",
        "Nigeria", //"NG",
        "Niue", //"NU",
// "Norfolk Island", //"NF",
        "Northern Mariana Islands", //"MP",
        "Norway", //"NO",
        "Oman", //"OM",
        "Pakistan", //"PK",
        "Palau", //"PW",
        "Palestinian Territory, Occupied", //"PS",
        "Panama", //"PA",
        "Papua New Guinea", //"PG",
        "Paraguay", //"PY",
        "Peru", //"PE",
        "Philippines", //"PH",
// "Pitcairn", //"PN",
        "Poland", //"PL",
        "Portugal", //"PT",
        "Puerto Rico", //"PR",
        "Qatar", //"QA",
        "Reunion", //"RE",
        "Romania", //"RO",
        "Russian Federation", //"RU",
        "Rwanda", //"RW",
        "Saint Barthelemy", //"BL",
// "Saint Helena Ascension and Tristan Da Cunha", //"SH",
        "Saint Kitts and Nevis", //"KN",
        "Saint Lucia", //"LC",
        "Saint Martin (French Part)", //"MF",
// "Saint Pierre and Miquelon", //"PM",
        "Saint Vincent and The Grenadines", //"VC",
        "Samoa", //"WS",
        "San Marino", //"SM",
        "Sao Tome and Principe", //"ST",
        "Saudi Arabia", //"SA",
        "Senegal", //"SN",
        "Serbia", //"RS",
        "Seychelles", //"SC",
        "Sierra Leone", //"SL",
        "Singapore", //"SG",
        "Sint Maarten (Dutch Part)", //"SX",
        "Slovakia", //"SK",
        "Slovenia", //"SI",
        "Solomon Islands", //"SB",
        "Somalia", //"SO",
        "South Africa", //"ZA",
// "South Georgia and The South Sandwich Islands", //"GS",
        "South Sudan", //"SS",
        "Spain", //"ES",
        "Sri Lanka", //"LK",
        "Sudan", //"SD",
        "Suriname", //"SR",
        "Swaziland", //"SZ",
        "Sweden", //"SE",
        "Switzerland", //"CH",
        "Syrian Arab Republic", //"SY",
        "Taiwan", //"TW",
        "Tajikistan", //"TJ",
        "United Republic of Tanzania", //"TZ",
        "Thailand", //"TH",
        "Timor-leste", //"TL",
        "Togo", //"TG",
// "Tokelau", //"TK",
        "Tonga", //"TO",
        "Trinidad and Tobago", //"TT",
        "Tunisia", //"TN",
        "Turkey", //"TR",
        "Turkmenistan", //"TM",
        "Turks and Caicos Islands", //"TC",
        "Tuvalu", //"TV",
        "Uganda", //"UG",
        "Ukraine", //"UA",
        "United Arab Emirates", //"AE",
        "United Kingdom", //"GB",
        "United States", //"US",
// "United States Minor Outlying Islands", //"UM",
        "Uruguay", //"UY",
        "Uzbekistan", //"UZ",
        "Vanuatu", //"VU",
        "Bolivarian Republic of Venezuela", //"VE",
        "Viet Nam", //"VN",
        "Virgin Islands, British", //"VG",
        "Virgin Islands, U.S.", //"VI",
// "Wallis and Futuna", //"WF",
        "Western Sahara", //"EH",
        "Yemen", //"YE",
        "Zambia", //"ZM",
        "Zimbabwe", //"ZW",
    };

    [ContextMenu("Execute")]

    public void Execute()
    {
        string[] guids2 = AssetDatabase.FindAssets("t:texture2D", new[] { "Assets\\FishPin\\Sprites\\CountryIcon" });
        for (int i = 0; i < 230; i++)
        {
            countries[i].countryCode = (ECountryCode)i;
            countries[i].countryName = countryName[i];

            for (int j = 0; j < guids2.Length; j++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids2[j]);
                if (countries[i].countryCode.ToString() == Path.GetFileNameWithoutExtension(path))
                {
                    countries[i].flag = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                }
            }
        }

    }
#endif
}

[System.Serializable]
public class Country
{
    public string countryName;
    public ECountryCode countryCode;
    public Sprite flag;
}
public enum ECountryCode
{
/* "Afghanistan*/ AF,
/* "Aland Islands*/ AX,
/* "Albania*/ AL,
/* "Algeria*/ DZ,
/* "American Samoa*/ AS,
/* "Andorra*/ AD,
/* "Angola*/ AO,
/* "Anguilla*/ AI,
/* "Antigua and Barbuda*/ AG,
/* "Argentina*/ AR,
/* "Armenia*/ AM,
/* "Aruba*/ AW,
/* "Australia*/ AU,
/* "Austria*/ AT,
/* "Azerbaijan*/ AZ,
/* "Bahamas*/ BS,
/* "Bahrain*/ BH,
/* "Bangladesh*/ BD,
/* "Barbados*/ BB,
/* "Belarus*/ BY,
/* "Belgium*/ BE,
/* "Belize*/ BZ,
/* "Benin*/ BJ,
/* "Bermuda*/ BM,
/* "Bhutan*/ BT,
/* "Bolivia, Plurinational State of*/ BO,
/* "Bonaire, Sint Eustatius and Saba*/ BQ,
/* "Bosnia and Herzegovina*/ BA,
/* "Botswana*/ BW,
/* "Brazil*/ BR,
/* "Brunei Darussalam*/ BN,
/* "Bulgaria*/ BG,
/* "Burkina Faso*/ BF,
/* "Burundi*/ BI,
/* "Cambodia*/ KH,
/* "Cameroon*/ CM,
/* "Canada*/ CA,
/* "Cape Verde*/ CV,
/* "Cayman Islands*/ KY,
/* "Central African Republic*/ CF,
/* "Chad*/ TD,
/* "Chile*/ CL,
/* "China*/ CN,
/* "Colombia*/ CO,
/* "Comoros*/ KM,
/* "Congo*/ CG,
/* "Congo, The Democratic Republic of The*/ CD,
/* "Cook Islands*/ CK,
/* "Costa Rica*/ CR,
/* "Cote D'ivoire*/ CI,
/* "Croatia*/ HR,
/* "Cuba*/ CU,
/* "Curacao*/ CW,
/* "Cyprus*/ CY,
/* "Czech Republic*/ CZ,
/* "Denmark*/ DK,
/* "Djibouti*/ DJ,
/* "Dominica*/ DM,
/* "Dominican Republic*/ DO,
/* "Ecuador*/ EC,
/* "Egypt*/ EG,
/* "El Salvador*/ SV,
/* "Equatorial Guinea*/ GQ,
/* "Eritrea*/ ER,
/* "Estonia*/ EE,
/* "Ethiopia*/ ET,
/* "Faroe Islands*/ FO,
/* "Fiji*/ FJ,
/* "Finland*/ FI,
/* "France*/ FR,
/* "French Guiana*/ GF,
/* "French Polynesia*/ PF,
/* "Gabon*/ GA,
/* "Gambia*/ GM,
/* "Georgia*/ GE,
/* "Germany*/ DE,
/* "Ghana*/ GH,
/* "Gibraltar*/ GI,
/* "Greece*/ GR,
/* "Greenland*/ GL,
/* "Grenada*/ GD,
/* "Guadeloupe*/ GP,
/* "Guam*/ GU,
/* "Guatemala*/ GT,
/* "Guernsey*/ GG,
/* "Guinea*/ GN,
/* "Guinea-Bissau*/ GW,
/* "Guyana*/ GY,
/* "Haiti*/ HT,
/* "Honduras*/ HN,
/* "Hong Kong*/ HK,
/* "Hungary*/ HU,
/* "Iceland*/ IS,
/* "India*/ IN,
/* "Indonesia*/ ID,
/* "Iran, Islamic Republic of*/ IR,
/* "Iraq*/ IQ,
/* "Ireland*/ IE,
/* "Israel*/ IL,
/* "Italy*/ IT,
/* "Jamaica*/ JM,
/* "Japan*/ JP,
/* "Jersey*/ JE,
/* "Jordan*/ JO,
/* "Kazakhstan*/ KZ,
/* "Kenya*/ KE,
/* "Kiribati*/ KI,
/* "Korea, Republic of*/ KR, XK,
/* "Kuwait*/ KW,
/* "Kyrgyzstan*/ KG,
/* "Lao People's Democratic Republic*/ LA,
/* "Latvia*/ LV,
/* "Lebanon*/ LB,
/* "Lesotho*/ LS,
/* "Liberia*/ LR,
/* "Libya*/ LY,
/* "Liechtenstein*/ LI,
/* "Lithuania*/ LT,
/* "Luxembourg*/ LU,
/* "Macao*/ MO,
/* "Macedonia, The Former Yugoslav Republic of*/ MK,
/* "Madagascar*/ MG,
/* "Malawi*/ MW,
/* "Malaysia*/ MY,
/* "Maldives*/ MV,
/* "Mali*/ ML,
/* "Malta*/ MT,
/* "Marshall Islands*/ MH,
/* "Martinique*/ MQ,
/* "Mauritania*/ MR,
/* "Mauritius*/ MU,
/* "Mayotte*/ YT,
/* "Mexico*/ MX,
/* "Micronesia, Federated States of*/ FM,
/* "Moldova, Republic of*/ MD,
/* "Monaco*/ MC,
/* "Mongolia*/ MN,
/* "Montenegro*/ ME,
/* "Montserrat*/ MS,
/* "Morocco*/ MA,
/* "Mozambique*/ MZ,
/* "Myanmar*/ MM,
/* "Namibia*/ NA,
/* "Nauru*/ NR,
/* "Nepal*/ NP,
/* "Netherlands*/ NL,
/* "New Caledonia*/ NC,
/* "New Zealand*/ NZ,
/* "Nicaragua*/ NI,
/* "Niger*/ NE,
/* "Nigeria*/ NG,
/* "Niue*/ NU,
/* "Northern Mariana Islands*/ MP,
/* "Norway*/ NO,
/* "Oman*/ OM,
/* "Pakistan*/PK,
/* "Palau*/ PW,
/* "Palestinian Territory, Occupied*/ PS,
/* "Panama*/ PA,
/* "Papua New Guinea*/ PG,
/* "Paraguay*/ PY,
/* "Peru*/ PE,
/* "Philippines*/ PH,
/* "Poland*/ PL,
/* "Portugal*/ PT,
/* "Puerto Rico*/ PR,
/* "Qatar*/ QA,
/* "Reunion*/ RE,
/* "Romania*/ RO,
/* "Russian Federation*/ RU,
/* "Rwanda*/ RW,
/* "Saint Barthelemy*/ BL,
/* "Saint Kitts and Nevis*/ KN,
/* "Saint Lucia*/ LC,
/* "Saint Martin (French Part)*/ MF,
/* "Saint Vincent and The Grenadines*/ VC,
/* "Samoa*/ WS,
/* "San Marino*/ SM,
/* "Sao Tome and Principe*/ ST,
/* "Saudi Arabia*/ SA,
/* "Senegal*/ SN,
/* "Serbia*/ RS,
/* "Seychelles*/ SC,
/* "Sierra Leone*/ SL,
/* "Singapore*/ SG,
/* "Sint Maarten (Dutch Part)*/ SX,
/* "Slovakia*/ SK,
/* "Slovenia*/ SI,
/* "Solomon Islands*/ SB,
/* "Somalia*/ SO,
/* "South Africa*/ ZA,
/* "South Sudan*/ SS,
/* "Spain*/ ES,
/* "Sri Lanka*/ LK,
/* "Sudan*/ SD,
/* "Suriname*/ SR,
/* "Swaziland*/ SZ,
/* "Sweden*/ SE,
/* "Switzerland*/ CH,
/* "Syrian Arab Republic*/ SY,
/* "Taiwan*/ TW,
/* "Tajikistan*/ TJ,
/* "Tanzania, United Republic of*/ TZ,
/* "Thailand*/ TH,
/* "Timor-leste*/ TL,
/* "Togo*/ TG,
/* "Tonga*/ TO,
/* "Trinidad and Tobago*/ TT,
/* "Tunisia*/ TN,
/* "Turkey*/ TR,
/* "Turkmenistan*/ TM,
/* "Turks and Caicos Islands*/ TC,
/* "Tuvalu*/ TV,
/* "Uganda*/ UG,
/* "Ukraine*/ UA,
/* "United Arab Emirates*/ AE,
/* "United Kingdom*/ GB,
/* "United States*/ US,
/* "Uruguay*/ UY,
/* "Uzbekistan*/ UZ,
/* "Vanuatu*/ VU,
/* "Venezuela, Bolivarian Republic of*/ VE,
/* "Viet Nam*/ VN,
/* "Virgin Islands, British*/ VG,
/* "Virgin Islands, U.S.*/ VI,
/* "Western Sahara*/ EH,
/* "Yemen*/ YE,
/* "Zambia*/ ZM,
/* "Zimbabwe*/ ZW,
    };


